### ISSUE TITLE
[docs] Debug mode link

### ISSUE THREAD

**Issue by dartess** [javierbrea/eslint-plugin-boundaries#160]
README.MD: link https://github.com/javierbrea/eslint-plugin-boundaries/blob/master/debug-mode is 404

also in https://github.com/javierbrea/eslint-plugin-boundaries/blob/master/docs/rules/element-types.md

**Comment by javierbrea** [comment]
Hi @dartess, thanks for notifying it! 😃 
It has been fixed in [release v2.5.1](https://github.com/javierbrea/eslint-plugin-boundaries/releases/tag/v2.5.1)

**Comment by dartess** [comment]
@javierbrea hi! thanks for your work!

I'm don't want to open new issue, but i fount another broken link:

page: https://github.com/javierbrea/eslint-plugin-boundaries/blob/master/docs/rules/element-types.md 
link: Further reading > Element matchers

**Comment by javierbrea** [comment]
Hi again @dartess, thanks again for the notice! 😃 
I'm just about to release a new version which will include custom error messages. I will fix this link and review all of the rest in that version also.
