### ISSUE TITLE
External Imports Ignored Due To Cache

### ISSUE THREAD

**Issue by jablonnc** [javierbrea/eslint-plugin-boundaries#260]
**Describe the bug**

When I define 2+ custom externals (i.e. not npm packages, but externals that I have created and am loading in at the `runtime`), it appears this linting rule picks up the first one and ignores all subsequent imports. After investigating, it appears to be related to the caching mechanism.

**To Reproduce**

In the `boundaryTest.ts` file I setup I only have two imports shown here:
<img width="506" alt="Screen Shot 2022-11-23 at 10 22 13 AM" src="https://user-images.githubusercontent.com/1964654/203583726-2250d98d-54fe-45b4-bdfd-cbd16f8be704.png">

For the two imports above, I have these added to the `import/no-unresolved` rule as shown here since they are modules consumed at the runtime:
<img width="279" alt="Screen Shot 2022-11-23 at 3 33 38 PM" src="https://user-images.githubusercontent.com/1964654/203641245-076390d3-68f7-4426-bdf5-574a22cf7705.png">

I have a relatively simple setup when it comes to the boundary rule:
<img width="399" alt="Screen Shot 2022-11-23 at 10 21 26 AM" src="https://user-images.githubusercontent.com/1964654/203583444-1447d74f-eab3-4cf8-81f7-e8e402df5771.png">

Upon running `yarn lint`, I only ever see an error message around the first external import I disallowed (in this case `web-runtime-commons-constants`):
<img width="1102" alt="Screen Shot 2022-11-23 at 10 23 41 AM" src="https://user-images.githubusercontent.com/1964654/203583919-335b02a1-b561-4136-8292-756f44c8d708.png">

**Expected behavior**

I would expect it to show an error message for both external imports.

**Additional context**

After debugging the issue, it seems related to the [following PR](https://github.com/javierbrea/eslint-plugin-boundaries/pull/144) where the cache was added. Specifically the `isExternal` prop is never added to the second import because after the cache is hit the first time (using the key `src/boundaryTest.ts`) it never proceeds to the second import in which it would get added:

<img width="625" alt="Screen Shot 2022-11-23 at 10 27 30 AM" src="https://user-images.githubusercontent.com/1964654/203584809-7d0aac88-4335-4b34-8e4e-fafad6be35d8.png">

I am actually able to fix this using the following approaches:
- Simply disable the `importsCache.save` on line 228.
- I can also fix this by downgrading the version of my lib to `2.3.0`, which is a state of the lib before the cache was introduced.
- Adding a reference to the module in `compilerOptions.paths` within tsconfig.json. However I don't really want to do this as I'm informing eslint to ignore this by adding these modules to the `import/no-unresolved` rule in my eslint config.

**Comment by javierbrea** [comment]
Hi @jablonnc, thank you very much for the detailed information about the issue. It has been fixed and will be released in v3.1.0.
