### ISSUE TITLE
Matching paths in external modules

### ISSUE THREAD

**Issue by butzist** [javierbrea/eslint-plugin-boundaries#297]
Thanks a lot for this plugin - it has been very useful so far.
I have a question though related to the following usecase:

We are moving some elements to a shared library and would like to enforce the same rules, that we have inside the sources, e.g. from: "components", disallow: "repositories".

This is what I came up with so far - which is not working:

```
    "boundaries/external": [
      "error",
      {
        default: "allow",
        rules: [
          {
            from: ["components"],
            disallow: ["@group/package/repositories/*"],
          },
        ],
      },
    ],
```

Is there any way to specify the allowed paths in a module?

**Comment by javierbrea** [comment]
Hi @butzist , when the imported library is outside the project it is considered "external", so, you should use the [external rule](https://github.com/javierbrea/eslint-plugin-boundaries/blob/master/docs/rules/external.md) to allow or disallow imports. You can configure it also using micromatch patterns, or even allow/disallow importing specific variables when using destructured imports.

**Comment by butzist** [comment]
Thank you for your answer @javierbrea - I have tried micromatch patterns, but it seems like they are only applied to the package name and not to the esm path inside the package. An example:

I have the following piece of code:

![image](https://github.com/javierbrea/eslint-plugin-boundaries/assets/2405792/540cd074-635e-4bcf-a9de-fb6095e91cfc)


The following rule unfortunately does not result in a eslint error:

```
    "boundaries/external": [
      "error",
      {
        default: "allow",
        rules: [
          {
            from: ["components"],
            disallow: ["@datahow/dhljs/services/**/*"],
          },
        ],
      },
    ],
```

whereas the following rule works, but seems to be only matching on the package name - not on the path:

```
    "boundaries/external": [
      "error",
      {
        default: "allow",
        rules: [
          {
            from: ["components"],
            disallow: ["@datahow/*"],
          },
        ],
      },
    ]
```

results in:

![image](https://github.com/javierbrea/eslint-plugin-boundaries/assets/2405792/9f1f3d84-ee88-4617-9bed-404dfa02d8e5)

**Comment by javierbrea** [comment]
Hi @butzist , sorry, you're right, it only takes into account the module name. In order to avoid a breaking change, I'm adding a `path` option that may be used to match the module path using micromatch patterns. For example:

```js
{
"boundaries/external": [
      "error",
      {
        default: "allow",
        rules: [
          {
            from: ["components"],
            disallow: [
                ["@datahow/dhljs", { path: "/services/*" }]
             ],
          },
        ],
      },
    ],
}
```

**Comment by butzist** [comment]
Awesome, thanks a lot @javierbrea! Will test this today.
