### ISSUE TITLE
Specify which element type has issues during settings validation

### ISSUE THREAD

**Issue by hmnzr** [javierbrea/eslint-plugin-boundaries#323]
**Is your feature request related to a problem? Please describe.**
Just installed the plugin and attempting configure the rules for the first time. I spent some time trying to understand which element causes this validation message `[boundaries]: Please provide a valid pattern in 'boundaries/elements' setting`. 

Having the type in the error message would've helped me to identify the issue faster.

**Describe the solution you'd like**
Include the element type in the settings validation message

**Describe alternatives you've considered**
None

**Additional context**
Raised a PR to address #324

**Comment by javierbrea** [comment]
Hi @hmnzr , thanks for your contribution! I will try to merge the PR as soon as possible and include it in the next release 😃.
