### ISSUE TITLE
plugin not working in vscode

### ISSUE THREAD

**Issue by abhijithhegde** [javierbrea/eslint-plugin-boundaries#347]
**Environment Details:**

Operating System: Windows 10 Home
Node.js Version: 20.16.0
npm Version: 10.8.1
ESLint Version: 8.0

**Issue Description:**
I am using the latest versions of the plugin. When there are errors such as _boundaries/element-types_  or _boundaries/no-unknown-files_ running the command **npm run lint** shows errors related to ESLint. But vscode is not showing them.

**Comment by abhijithhegde** [comment]
It works fine when there is only one eslint config, but in workspaces with multiple projects, it fails to show errors

**Comment by Manu639** [comment]
You should configure your "eslint.workingDirectories" setting on settings.json inside the .vscode folder of your workspace.

That is the setting you use to tell Eslint where it shoud find the root config file.
