### ISSUE TITLE
Ignore setting not working in Visual Studio Code on Windows OS

### ISSUE THREAD

**Issue by javierbrea** [javierbrea/eslint-plugin-boundaries#60]
The `boundaries/ignore` setting is not working on Windows OS when opening a file in Visual Studio Code.

This issue has been reported by @lichblitz, who gets an error of type `File does not belong to any element type` (from the `prefer-recognized-types` rule) when he opens an ignored file in Visual Studio Code on Windows.

**Comment by javierbrea** [comment]
Please, @lichblitz, I need additional info, could you answer some questions?
* Does the `npm run lint` command work as expected? I mean, is the error produced only in the IDE?
* In case the answer of the first question is positive, have you tried with a different IDE? Do you receive the same error in that case?

**Comment by lichblitz** [comment]
Hi @javierbrea :
* ```npm run lint ``` runs properly in the console.
* I tried it on Atom IDE and the configuration looks good. There are no errors on the ignored files. Also I removed some folders from the ignore list config and the Eslint error shown properly.

Looks like there is some problem with the VS Code + Eslint Plugin configuration.

**Comment by javierbrea** [comment]
Does the other plugin configuration work properly? For example, if you add a forbidden dependency producing an error in the `boundaries/allowed-types` rule, or you add a forbidden dependency by the `bounderaies/no-external` rule, is the IDE detecting properly the eslint errors?

**Comment by javierbrea** [comment]
Hi @lichblitz, do you still have the problem using  version [v2.0.0-beta.3](https://github.com/javierbrea/eslint-plugin-boundaries/releases/tag/v2.0.0-beta.3)?

**Comment by javierbrea** [comment]
Hi again @lichblitz, any news on this?

**Comment by lichblitz** [comment]
Hi @javierbrea Yes, I am having two problems:
1. Ignores still not working:
![Captura1](https://user-images.githubusercontent.com/6466976/112704937-8a209200-8e6a-11eb-9cad-eefa8efd2292.PNG)

2. Some imports are ignored. I launched "npm i" but still:
![Captura2](https://user-images.githubusercontent.com/6466976/112704985-cb18a680-8e6a-11eb-830b-08237f4617dc.PNG)

I made some additional configurations for the VS:Eslint plugin with ".vscode" settings folder. And made some changes to boundaries in the eslint config file just to test and it detects lint errors. Also the npm command for linting runs well.

**Comment by javierbrea** [comment]
Hi @lichblitz , I'm not able to reproduce the issue.

Maybe the config was changed but VsCode was not reloaded? Note that sometimes, when changing configurations it is needed to close VSCode and reopen it, or make `CTRL+Shif+P` -> Reload Window.

**Comment by javierbrea** [comment]
Closed due to inactivity.
